# Generated by Django 4.2.2 on 2023-07-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_pin",
                    models.CharField(
                        blank=True,
                        help_text="set pin to verify the password",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserPin",
                "verbose_name_plural": "UserPins",
            },
        ),
        migrations.CreateModel(
            name="Entries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True,
                        help_text="name set in the web while registration",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_url",
                    models.URLField(
                        blank=True,
                        help_text="url of the app of web",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_username",
                    models.CharField(
                        blank=True,
                        help_text="username set in a web or app",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_email",
                    models.CharField(
                        blank=True,
                        help_text="email set in a web or app",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_password",
                    models.CharField(
                        blank=True,
                        help_text="password set in a web or an app",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserEntry",
                "verbose_name_plural": "UserEntries",
                "unique_together": {("user", "app_name", "app_url")},
            },
        ),
    ]
